import { City, PropertyType, BHK, Purpose, Timeline, Source, Status } from "@prisma/client";

export const fakeBuyers = [
  {
    fullName: "Alice Johnson",
    email: "alice@example.com",
    phone: "9876543210",
    city: City.CHANDIGARH,
    propertyType: PropertyType.APARTMENT,
    bhk: BHK.TWO,
    purpose: Purpose.BUY,
    budgetMin: 5000000,
    budgetMax: 8000000,
    timeline: Timeline.ZERO_TO_3M,
    source: Source.WEBSITE,
    status: Status.NEW,
    notes: "VIP client",
    tags: ["VIP", "Priority"]
  },
  {
    fullName: "Bob Smith",
    email: "bob@example.com",
    phone: "9876543211",
    city: City.MOHALI,
    propertyType: PropertyType.VILLA,
    bhk: BHK.FOUR,
    purpose: Purpose.BUY,
    budgetMin: 15000000,
    budgetMax: 25000000,
    timeline: Timeline.THREE_TO_6M,
    source: Source.REFERRAL,
    status: Status.QUALIFIED,
    notes: "Looking for a big garden",
    tags: ["Referral"]
  },
  {
    fullName: "Charlie Lee",
    email: "charlie@example.com",
    phone: "9876543212",
    city: City.ZIRAKPUR,
    propertyType: PropertyType.PLOT,
    bhk: null,
    purpose: Purpose.BUY,
    budgetMin: 2000000,
    budgetMax: 4000000,
    timeline: Timeline.EXPLORING,
    source: Source.WALKIN,
    status: Status.CONTACTED,
    notes: "Wants a corner plot",
    tags: ["Walk-in"]
  },
  {
    fullName: "Diana Prince",
    email: "diana@example.com",
    phone: "9876543213",
    city: City.PANCHKULA,
    propertyType: PropertyType.APARTMENT,
    bhk: BHK.THREE,
    purpose: Purpose.RENT,
    budgetMin: 30000,
    budgetMax: 50000,
    timeline: Timeline.ZERO_TO_3M,
    source: Source.CALL,
    status: Status.NEW,
    notes: "",
    tags: ["Follow-up"]
  },
  {
    fullName: "Edward Norton",
    email: "edward@example.com",
    phone: "9876543214",
    city: City.OTHER,
    propertyType: PropertyType.RETAIL,
    bhk: null,
    purpose: Purpose.BUY,
    budgetMin: 1000000,
    budgetMax: 2000000,
    timeline: Timeline.GT_6M,
    source: Source.WEBSITE,
    status: Status.NEW,
    notes: "Interested in commercial space",
    tags: ["Commercial"]
  },
  {
    fullName: "Fiona Gallagher",
    email: "fiona@example.com",
    phone: "9876543215",
    city: City.CHANDIGARH,
    propertyType: PropertyType.VILLA,
    bhk: BHK.THREE,
    purpose: Purpose.RENT,
    budgetMin: 60000,
    budgetMax: 90000,
    timeline: Timeline.ZERO_TO_3M,
    source: Source.REFERRAL,
    status: Status.CONTACTED,
    notes: "",
    tags: ["Priority"]
  },
  {
    fullName: "George Michael",
    email: "george@example.com",
    phone: "9876543216",
    city: City.MOHALI,
    propertyType: PropertyType.OFFICE,
    bhk: null,
    purpose: Purpose.BUY,
    budgetMin: 5000000,
    budgetMax: 10000000,
    timeline: Timeline.THREE_TO_6M,
    source: Source.CALL,
    status: Status.QUALIFIED,
    notes: "",
    tags: ["Office"]
  },
  {
    fullName: "Hannah Baker",
    email: "hannah@example.com",
    phone: "9876543217",
    city: City.ZIRAKPUR,
    propertyType: PropertyType.APARTMENT,
    bhk: BHK.STUDIO,
    purpose: Purpose.RENT,
    budgetMin: 20000,
    budgetMax: 35000,
    timeline: Timeline.ZERO_TO_3M,
    source: Source.WALKIN,
    status: Status.NEW,
    notes: "",
    tags: ["Studio"]
  },
  {
    fullName: "Ian Somerhalder",
    email: "ian@example.com",
    phone: "9876543218",
    city: City.PANCHKULA,
    propertyType: PropertyType.PLOT,
    bhk: null,
    purpose: Purpose.BUY,
    budgetMin: 3000000,
    budgetMax: 5000000,
    timeline: Timeline.GT_6M,
    source: Source.OTHER,
    status: Status.NEW,
    notes: "Looking for outskirts",
    tags: ["Plot"]
  },
  {
    fullName: "Julia Roberts",
    email: "julia@example.com",
    phone: "9876543219",
    city: City.CHANDIGARH,
    propertyType: PropertyType.VILLA,
    bhk: BHK.FOUR,
    purpose: Purpose.BUY,
    budgetMin: 20000000,
    budgetMax: 30000000,
    timeline: Timeline.THREE_TO_6M,
    source: Source.WEBSITE,
    status: Status.NEW,
    notes: "",
    tags: ["Luxury"]
  },
];